// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dwjfnlppidvmtggieztd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3amZubHBwaWR2bXRnZ2llenRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNTg5NzksImV4cCI6MjA3NDczNDk3OX0.GnR-CVFXx5jSufKmJqZxMf1nYn3UTRAkEjM2t6lQZVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);